import { Inter } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";

// Use Inter font with latin subset
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        
        <link
        href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&family=Yuji+Mai:ital,wght@0,400;1,400&display=swap"
        rel="stylesheet"
/>

      </head>
      <body className={`${inter.className} font-poppins`}>{children}</body>
    </html>
  );
}
